name: Scrape Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * *'

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.4.0
      - run: npm i
      - run: npm run scrape
