name: Check Prettier Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run format:check
