name: Check Prettier Format

on:
  workflow_dispatch:
    inputs:
      npmRunArgs:
        required: false
        description: The args for `npm run`
        default: format:check
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ory/prettier-styles@v1
        with:
          npmRunArgs: ${{ github.event.inputs.npmRunArgs || "format:check" }}
