name: Check Prettier Format

on:
  workflow_dispatch:
    inputs:
      npmRunArgs:
        required: false
        description: The args for `npm run`
        default: format:check
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ory/prettier-styles@v1
        with:
          npmRunArgs: ${{ github.event.inputs.npmRunArgs || 'format:check' }}
      - run: |-
          git config --local user.email "zepatrik@users.noreply.github.com"
          git config --local user.name "zepatrik"
          git add .
          git diff --cached --exit-code && git commit -a -m "autogen: run npm format" && git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF#"refs/heads/"} || true
